### ISSUE TITLE
Errors when running demo

### ISSUE THREAD

**Issue by nbardy** [josephrocca/openai-clip-js#2]
I'm getting an error when running the text model in chrome.

<img width="499" alt="Screen Shot 2022-04-29 at 9 24 31 AM" src="https://user-images.githubusercontent.com/1278972/165984875-204cc9a2-d450-49f4-ade3-92f90b286bd7.png">

The image model runs successfully on wasm, but fails on webgl
<img width="497" alt="Screen Shot 2022-04-29 at 9 25 49 AM" src="https://user-images.githubusercontent.com/1278972/165985086-e9d26cb6-5309-440b-9721-a10140b80103.png">

**Comment by nbardy** [comment]
The CLIP search demo works, so it must just be an issue with the images

**Comment by josephrocca** [comment]
Ah yeah sorry the WebGL backend doesn't work due to conversion issues (I've added a message now to point that out). Not sure how much extra model conversion fiddling it would take to get it going since it's a serial chain so I don't know if there's 10 more to solve after fixing that one. In general though it always ends up being a lot harder to get WebGL working compared to Wasm. Wasm has more op support because they compile the C/C++ runtime directly in case of onnx and tflite. Hoping that when we get WebGPU, it'll have high op coverage for the same reason as Wasm - guessing it should be possible to directly port the GPU kernels.

Problem with the text model should be fixed now too. Thanks! (feel free to re-open if it's still not working for you)

**Comment by nbardy** [comment]
I ran into the same serial issue thing and just gave up. Kudos for getting this far
